AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  samaya_project

  Sample SAM Template for samaya_project
  
Globals:
  Function:
    Timeout: 3

Parameters:
  twitterBearerToken:
    Type: String
  twitterEndPoint:
    type: String

Resources:
  TwitterFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: twitter/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
          twitterBearerToken: !Ref twitterBearerToken
          twitterEndPoint: !Ref twitterEndPoint
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /services/tweets
            Method: get

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  TwitterFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt TwitterFunction.Arn
  TwitterFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt TwitterFunctionRole.Arn
